CREATE TABLE IF NOT EXISTS users
(
    id       BINARY(16) PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email    VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
